force-app/main/default/objects/Mission_Assignment__c/Mission_Assignment__c.object-meta.xml
<CustomObject>
    <label>Mission Assignment</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Mission Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mission Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Superhero_Mission__c/Superhero_Mission__c.object-meta.xml
<CustomObject>
    <label>Superhero Mission</label>
    <nameField>
        <displayFormat>SM-{0000}</displayFormat>
        <label>Superhero Mission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Superhero Missions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Superhero_Mission__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MissionDetailController.cls
public with sharing class MissionDetailController {

    @AuraEnabled(cacheable=true)
    public static  Map<String, SObject> getMissionAssignment(Id missionId){
        try {
            Hero__c hero = SelectorHelper.getHeroByCurrentUser();
            Superhero_Mission__c mission = WithoutSharingSelector.getHeroMissionById(missionId);
            Mission_Assignment__c assignment = SelectorHelper.getMissionAssignment(hero.Id, missionId);

            Map<String, SObject> responseMap = new Map<String, SObject>();
            //todo remove hardcode
            responseMap.put('mission',mission);
            responseMap.put('assignment',assignment);
            return responseMap;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Mission_Assignment__c createAssignment(String missionId){
        try {
            Hero__c hero = SelectorHelper.getHeroByCurrentUser();
            Mission_Assignment__c missionAssignment = new Mission_Assignment__c();
            missionAssignment.Hero__c = hero.Id;
            missionAssignment.Mission__c = missionId;
            WithoutSharingSelector.insertRecords(new List<SObject> {missionAssignment});
            return SelectorHelper.getMissionAssignment(hero.Id, missionId);
        } catch (Exception e) {
           throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Mission_Assignment__c completeMission(String missionAssignmentId){
        try {
            Mission_Assignment__c missionAssignment = new Mission_Assignment__c();
            missionAssignment.Id = missionAssignmentId;
            missionAssignment.Status__c = ConstantsHelper.COMPLETED_STATUS;
            update missionAssignment;
            return missionAssignment;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}