force-app/main/default/objects/Mission_Assignment__c/Mission_Assignment__c.object-meta.xml
<CustomObject>
    <label>Mission Assignment</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Mission Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mission Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Superhero_Mission__c/Superhero_Mission__c.object-meta.xml
<CustomObject>
    <label>Superhero Mission</label>
    <nameField>
        <displayFormat>SM-{0000}</displayFormat>
        <label>Superhero Mission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Superhero Missions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Superhero_Mission__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MissionAssignmentTriggerHandlerTest.cls
@isTest
public with sharing class MissionAssignmentTriggerHandlerTest {
    @TestSetup
    static void makeData(){
        TestHelper.generateData();
    }

    @isTest 
    static void testValidateAssignments() {
        User testUser = [SELECT Id, ContactId FROM User WHERE UserName = 'yourusername@gmail.com' LIMIT 1];
        PermissionSet ps = [SELECT Id 
                    FROM PermissionSet 
                    WHERE Name = 'Hero_User'];
        insert new PermissionSetAssignment(AssigneeId = testUser.Id, PermissionSetId = ps.Id);
        System.runAs(testUser) {
            System.assertEquals(testUser.Id, UserInfo.getUserId(), 'User ID should match');
            Hero__c hero = SelectorHelper.getHeroByCurrentUser();
            List<Superhero_Mission__c> missionList = WithoutSharingSelector.getHeroMissionsForHero(testUser.ContactId);
            System.debug(missionList);
            System.assert(missionList.size() == TestHelper.MISSION_NUMBER_FOR_INSERT);

            //add first three missions
            MissionDetailController.createAssignment(missionList[0].Id);
            MissionDetailController.createAssignment(missionList[1].Id);
            MissionDetailController.createAssignment(missionList[2].Id);
            List<Mission_Assignment__c> assignmentList = [SELECT Id FROM Mission_Assignment__c WHERE Hero__c = :hero.Id];
            System.assert(assignmentList.size() == ConstantsHelper.MAX_MISSION_PER_USER);

            //add 4 mission should exeption
            try {
                MissionDetailController.createAssignment(missionList[3].Id);
                System.assert(false);
            } catch(Exception e) {
                System.assert(true);
            }

            
        }
    }

    @isTest 
    static void testNegtiveValidateMissionsAccess() {
        User testUser = [SELECT Id, ContactId FROM User WHERE UserName = 'yourusername@gmail.com' LIMIT 1];
        PermissionSet ps = [SELECT Id 
                    FROM PermissionSet 
                    WHERE Name = 'Hero_User'];
        insert new PermissionSetAssignment(AssigneeId = testUser.Id, PermissionSetId = ps.Id);
        System.runAs(testUser) {
            System.assertEquals(testUser.Id, UserInfo.getUserId(), 'User ID should match');
            //by default Hero has A rank
            Hero__c hero = SelectorHelper.getHeroByCurrentUser();
            hero.Rank__c = 'D';
            WithoutSharingSelector.updateRecords(new List<SObject> {hero});
            //by default Mission has B rank
            List<Superhero_Mission__c> missionList = WithoutSharingSelector.getHeroMissionsForHero(testUser.ContactId);
            System.assert(missionList.size() == TestHelper.MISSION_NUMBER_FOR_INSERT);
            //Becouse User has low rank He isn't able to take mission with B rank
            try {
                MissionDetailController.createAssignment(missionList[0].Id);
                System.assert(false);
            } catch(Exception e) {
                System.assert(true);
            }

            
        }
    }

    @isTest 
    static void testCompleteMissionWithOherUsers() {
        User testUser = [SELECT Id, ContactId FROM User WHERE UserName = 'yourusername@gmail.com' LIMIT 1];
        PermissionSet ps = [SELECT Id 
                    FROM PermissionSet 
                    WHERE Name = 'Hero_User'];
        insert new PermissionSetAssignment(AssigneeId = testUser.Id, PermissionSetId = ps.Id);
        System.runAs(testUser) {
            System.assertEquals(testUser.Id, UserInfo.getUserId(), 'User ID should match');
            Hero__c hero = SelectorHelper.getHeroByCurrentUser();
            List<Superhero_Mission__c> missionList = WithoutSharingSelector.getHeroMissionsForHero(testUser.ContactId);

            System.assert(missionList.size() == TestHelper.MISSION_NUMBER_FOR_INSERT);           

            Mission_Assignment__c assignment = MissionDetailController.createAssignment(missionList[0].Id);

            MissionDetailController.completeMission(assignment.Id);
            
            assignment = SelectorHelper.getMissionAssignment(assignment.Id);

            System.assert(assignment.Status__c == ConstantsHelper.COMPLETED_STATUS);

            Superhero_Mission__c mission = WithoutSharingSelector.getHeroMissionById(missionList[0].Id);

            System.assert(mission.Status__c == ConstantsHelper.COMPLETED_STATUS);


            
        }
    }

    @isTest 
    static void testCompleteMissions() {
        User testUser = [SELECT Id, ContactId FROM User WHERE UserName = 'yourusername@gmail.com' LIMIT 1];
        PermissionSet ps = [SELECT Id 
                    FROM PermissionSet 
                    WHERE Name = 'Hero_User'];
        insert new PermissionSetAssignment(AssigneeId = testUser.Id, PermissionSetId = ps.Id);
        System.runAs(testUser) {
            System.assertEquals(testUser.Id, UserInfo.getUserId(), 'User ID should match');
            Hero__c hero = SelectorHelper.getHeroByCurrentUser();
            List<Superhero_Mission__c> missionList = WithoutSharingSelector.getHeroMissionsForHero(testUser.ContactId);
            System.assert(missionList.size() == TestHelper.MISSION_NUMBER_FOR_INSERT);           

            Mission_Assignment__c assignment = MissionDetailController.createAssignment(missionList[0].Id);
            Hero__c otherHero = [SELECT Id FROM Hero__c WHERE Id != :hero.Id LIMIT 1];
            Mission_Assignment__c assignmentForOtherHero = new Mission_Assignment__c();
            assignmentForOtherHero.Hero__c = otherHero.Id;
            assignmentForOtherHero.Mission__c = missionList[0].Id;
            WithoutSharingSelector.insertRecords(new List<SObject> {assignmentForOtherHero});

            MissionDetailController.completeMission(assignment.Id);
            assignment = SelectorHelper.getMissionAssignment(assignment.Id);
            System.assert(assignment.Status__c == ConstantsHelper.COMPLETED_STATUS);
            Superhero_Mission__c mission = WithoutSharingSelector.getHeroMissionById(missionList[0].Id);
            System.assert(mission.Status__c == ConstantsHelper.COMPLETED_STATUS);
            
            assignmentForOtherHero = SelectorHelper.getMissionAssignment(assignmentForOtherHero.Id);
            System.assert(assignmentForOtherHero.Status__c == ConstantsHelper.FAILED_STATUS);

            
        }
    }
}