force-app/main/default/objects/Hero__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Heroes</relationshipLabel>
    <relationshipName>Heroes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mission_Assignment__c/Mission_Assignment__c.object-meta.xml
<CustomObject>
    <label>Mission Assignment</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Mission Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mission Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Superhero_Mission__c/Superhero_Mission__c.object-meta.xml
<CustomObject>
    <label>Superhero Mission</label>
    <nameField>
        <displayFormat>SM-{0000}</displayFormat>
        <label>Superhero Mission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Superhero Missions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Superhero_Mission__c/fields/Complexity_Rank__c.field-meta.xml
<CustomField>
    <fullName>Complexity_Rank__c</fullName>
    <label>Complexity Rank</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rank</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Superhero_Mission__c/fields/Guild__c.field-meta.xml
<CustomField>
    <fullName>Guild__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guild</label>
    <referenceTo>Guild__c</referenceTo>
    <relationshipLabel>Superhero Missions</relationshipLabel>
    <relationshipName>Superhero_Missions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Superhero_Mission__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SelectorHelper.cls
public with sharing class SelectorHelper {
    public static List<Superhero_Mission__c> getHeroMissions() {
        return [
            SELECT  Id, 
                    Complexity_Rank__c, 
                    Name, 
                    Guild__r.Name, 
                    Status__c, 
                    Subject__c 
            FROM    Superhero_Mission__c 
            ORDER   BY CreatedDate
            LIMIT   50000
        ];
    }

    public static Superhero_Mission__c getHeroMissionById(Id recordId) {
        return [
            SELECT  Id, 
                    Complexity_Rank__c, 
                    Name, 
                    Guild__r.Name, 
                    Status__c, 
                    Subject__c 
            FROM    Superhero_Mission__c 
            WHERE   Id = :recordId
            WITH    SECURITY_ENFORCED
            LIMIT   1
        ];
    }

    public static List<Superhero_Mission__c> getHeroMissionsByIds(List<Id> idList) {
        return [
            SELECT  Id, 
                    Complexity_Rank__c, 
                    Name, 
                    Guild__r.Name, 
                    Status__c, 
                    Subject__c 
            FROM    Superhero_Mission__c 
            WHERE   Id = : idList 
            WITH    SECURITY_ENFORCED
            LIMIT   50000 
            
        ];
    }

    public static List<Hero__c> getHeroesByIds(List<Id> idList) {
        return [
            SELECT  Id, 
                    Rank__c, 
                    Name, 
                    Contact__c
                     
            FROM    Hero__c 
            WHERE   Id = : idList
            WITH    SECURITY_ENFORCED
            LIMIT   50000
        ];
    }

    public static Mission_Assignment__c getMissionAssignment(String contactId, String missionId) {
        List<Mission_Assignment__c> assignmentList = [
            SELECT  Id, Status__c 
            FROM    Mission_Assignment__c 
            WHERE   Hero__c = :contactId 
            AND     Mission__c = :missionId
            WITH    SECURITY_ENFORCED
            LIMIT  1
        ];

        return assignmentList.size() > 0 ? assignmentList[0] : null;
    }

    public static Mission_Assignment__c getMissionAssignment(String assignmentId) {
        List<Mission_Assignment__c> assignmentList = [
            SELECT  Id, Status__c 
            FROM    Mission_Assignment__c 
            WHERE   Id = :assignmentId
            WITH    SECURITY_ENFORCED
            LIMIT  1
        ];

        return assignmentList.size() > 0 ? assignmentList[0] : null;
    }


    public static Hero__c getHeroByCurrentUser() {
        User customerUser = [SELECT id, ContactId FROM User WHERE Id =:UserInfo.getUserId() LIMIT 1];
        Id contactId = customerUser.contactId;
        return [
            SELECT  Id, Guild__c 
            FROM    HERO__c 
            WHERE   Contact__c = :contactId  
            WITH    SECURITY_ENFORCED 
            LIMIT   1
        ];
    }
}