force-app/main/default/objects/Superhero_Mission__c/Superhero_Mission__c.object-meta.xml
<CustomObject>
    <label>Superhero Mission</label>
    <nameField>
        <displayFormat>SM-{0000}</displayFormat>
        <label>Superhero Mission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Superhero Missions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Superhero_Mission__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MissionTriggerHandler.cls
public with sharing class MissionTriggerHandler {
    final static String EMAIL_MESSAGE = '{0} Mission was completed';
    final static String EMAIL_SUBJECT = 'Mission Completed';
    public static void onBeforeInsert(List<Superhero_Mission__c> newRecordList) {
    }

    public static void onBeforeUpdate(List<Superhero_Mission__c> updatedRecordList, Map<Id, Superhero_Mission__c> oldRecordMap) {
        
    }

    public static void onAfterInsert(List<Superhero_Mission__c> newRecordList) {
        sendEmailNotificatonToUsers(newRecordList);
    }

    public static void onAfterUpdate(List<Superhero_Mission__c> updatedRecordList, Map<Id, Superhero_Mission__c> oldRecordMap) {
        sendEmailNotificatonToOwner(updatedRecordList, oldRecordMap);
    }

    static void sendEmailNotificatonToUsers(List<Superhero_Mission__c> recordList) {
        Database.executeBatch(new EmailNotificationBatch(recordList), 200);
    }

    static void sendEmailNotificatonToOwner(List<Superhero_Mission__c> recordList, Map<Id, Superhero_Mission__c> oldRecordMap) {
        List<Messaging.SingleEmailMessage> masterListMails = new List<Messaging.SingleEmailMessage>();
        OrgWideEmailAddress emailAddress = [SELECT Id, Address, DisplayName FROM OrgWideEmailAddress WHERE DisplayName= :ConstantsHelper.SENDER_DISPLAY_NAME];
        for(Superhero_Mission__c mission : recordList) {
            if(mission.Status__c != oldRecordMap.get(mission.Id).Status__c && mission.Status__c == ConstantsHelper.COMPLETED_STATUS ) {
                Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                email.setSaveAsActivity(false);
                email.setTargetObjectId(mission.OwnerId);
                email.setOrgWideEmailAddressId(emailAddress.Id);
                email.setSubject(EMAIL_SUBJECT);
                email.setPlainTextBody(String.format(EMAIL_MESSAGE, new List<String> {mission.Subject__c}));
                masterListMails.add(email);
            }
                
        }
        WithoutSharingSelector.sendEmails(masterListMails);
    }
}